return {
    unitName = "missile_hemnok",
    unitDisplayName = "Solkata Missile",
    unitTooltip = "",
    unitBlurb = "Armour penetrating torpedo.",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_14019_missile_hemnok.png",
    controllable = false,
    unselectable = true,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 2204019,
        factionID = 220,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "0",
        requiredLevelForDescription = "",
        tactical = "",
        description = "",
        weaponInfo = {
            { 2205032, 1, 0 },
        },
    },
    scale = 0.07,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_missile_hemnok/01_missile_hemnok",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "thruster_glow",
            position = { 0, 0, -0.414 },
            rotation = { 0, 0, 0 },
            scale = { 0.2, 0.2, 0.75 },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_ultralowPoly/thrusterplume_utralowpolly",
                    materials = { "01_MT_ThrusterGlow_opaque_bright" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 2, 2, 1.5 },
                },
            },
        },
        {
            name = "warhead",
            position = { 0, 0, 0.11 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            weapon = {
                weaponID = 2205088,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
            },
        },
        {
            name = "ParticleEmitter",
            position = { 0, 0, -0.404 },
            rotation = { 0, 0, 0 },
            scale = { 1.571429, 1.571429, 1.571429 },
            particleEmitter = {
                particleType = "RIBBON",
                distancePerParticle = 0,
                minSecondsPerParticle = 0,
                ejectionVelocity = -1,
                ejectionVelocityAwayFromEmitter = false,
                randomRadius = 0,
                randomScaleMinFraction = 0,
                startDisabled = false,
                stateToggleTrigger = "None",
                colourStart = { 1, 1.5, 2 },
                colourEnd = { 0.5, 0.5, 0.5 },
                opacity = 0.5,
                scaleStart = 0.02,
                scaleEnd = 0,
                lifetime = 0.12,
            },
        },
    },
    unitCore = true,
    physicsShape = {
        shapeType = "Capsule",
        center = { 0, 0, 0 },
        radius = 0.2,
        height = 1,
        orientation = { 0, 0, 0 },
        collisionResponse = "Collide",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "MISSILE",
        health = 10,
        health_regen_per_second = 0,
        max_regen_frac = 0,
        armour = 0,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.3,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0.3,
        untargetableTime = 0.15,
        phaseBlockFraction = 0,
        lifetime = 4,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0.4,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 0,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "FREE",
        maximumAngleToTarget = 0.2,
        acceleration = 3.5,
        strafingAccelMultiplier = 0,
        reverseAccelMultiplier = 0,
        inertialCorrection = false,
        isStrafing = false,
        alwaysThrust = false,
        launchDumbThrustSeconds = 0,
        standoffDistance = 0,
        retreatDistance = 0,
        panicDistance = 0,
        unpanicDistance = 0,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        useMaximumWorldYPosition = false,
        minimumWorldYPosition = 0,
        maximumWorldYPosition = 0,
        forceFaceCombatTargetInDistance = 0,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 30,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = true,
    },
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = true,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 26,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = -0.05,
            scoreForAngle = 0,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 50,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 0.4,
            classMultMedium = 1,
            classMultHeavy = 1.25,
            classMultCapital = 1.25,
            classMultTitan = 1.25,
            shipMultiplier = 0,
            structureMultiplier = 0,
            keepTargetMultiplier = 20,
            scoreBandingSize = 0,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "MISSILE",
            predictionVelocityOveride = 0,
            predictionAcceleration = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
