return {
    unitName = "light_tolly",
    unitDisplayName = "Tolly",
    unitTooltip = "",
    unitBlurb = "Light Swarm Assault",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "T",
    picture = "1_11000_light_tolly.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 2201000,
        factionID = 220,
        macroType = "AUTO",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "<color=yellow>Swarm Assault</color>\n- Strong against Lights.\n- Decent against Mediums.\n- Poor against 20+ Armour.\n- Vulnerable to Drones.",
        description = "Dozens of attempts were made to improve upon the Tolly's design. The initial plan of adding cloaking fields to the ship was considered a failure after commanders complained about not being able to see their swarms fill the battlefield. Few other ideas were proposed due to the hyper-optimized design of the ship until one Platform Commander thought to, per their words, 'play' with Point-Shadow technology. \n\nBy utilizing the same technology that allows point-shadow orbs to track enemy vessels, the Tolly's hull is coated with a low-level field that repulses other Tollys. This is most pronounced when the charged debris forces nearby Tollys to scatter, limiting the affectiveness of anti-swarm weaponry.",
        weaponInfo = {
            { 2205000, 1, 0 },
        },
    },
    scale = 0.4,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 0.5,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_ship_light_tolly/01_ship_light_tolly",
    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_teamColour" },
    parts = {
        {
            name = "unitBubble",
            mesh = "01_ship_light_tolly/01_ship_light_tolly_aegis",
            materials = { "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.1, 1.1, 1.1 },
            aegisVisual = true,
        },
        {
            name = "thruster_glow",
            position = { 0, 0, -0.354 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1.45 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { -0.314, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.372893, 0.192, 0.372893 },
                },
                {
                    name = "glow (1)",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0.314, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.372893, 0.192, 0.372893 },
                },
            },
        },
        {
            name = "thruster_glow (2)",
            position = { 0.33, 0, -0.093 },
            rotation = { 0, 242.3225, 0 },
            scale = { 1, 1, 1.45 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.797071, 0.124113, 0.175828 },
                },
            },
        },
        {
            name = "thruster_glow (3)",
            position = { -0.33, 0, -0.093 },
            rotation = { 0, 117.678, 0 },
            scale = { 1, 1, 1.45 },
            thruster = {
                decayTime = 0.65,
                workWhenThrustWithinAngleDegrees = 63,
            },
            visibility = {
                visibleInEditor = false,
                visibleInGame = true,
            },
            parts = {
                {
                    name = "glow",
                    mesh = "thrusterplume_lowPoly/thrusterplume_lowpolly",
                    materials = { "01_MT_ThrusterGlow" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.797071, 0.124113, 0.175828 },
                },
            },
        },
        {
            name = "spinal gun",
            position = { 0, 0, 0.47579 },
            rotation = { 0, 0, 0 },
            scale = { 0.5, 0.5, 0.5 },
            weapon = {
                weaponID = 2205000,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = true,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 45,
                    right = 45,
                    up = 20,
                    down = 20,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.05, 0.05, 0.05 },
                    weaponVisualConfig = {
                        laserColour = { 0.3, 0.605233, 1, 1 },
                        intensity = 3,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
            },
        },
        {
            name = "deathflash",
            position = { 0, 0, -0.087 },
            rotation = { 0, 0, 0 },
            scale = { 0.15, 0.15, 0.15 },
            weapon = {
                weaponID = 0,
                turnSpeed = 0,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 0,
                    right = 0,
                    up = 0,
                    down = 0,
                },
                weaponData = {
                    weaponType = "SPARKLER",
                    alwaysfire = true,
                    magdump = false,
                    necrofire = true,
                    active = false,
                    oneuse = false,
                    exemptFromRangeSanityChecks = false,
                    rangeInUnits = 0,
                    maximumAngleToTarget = 0,
                    unitsPerSecond = 0,
                    spreadDegrees = 0,
                    spreadType = "BELLCURVE",
                    forceRaycastDirectlyToTarget = false,
                    lockTime = 0,
                    simultaniousObjectLimit = 0,
                    damageData = {
                        isNondamaging = false,
                        instances = 0,
                        damage = 0,
                        piercing = 0,
                        shred = 0,
                        heat = 0,
                        vulnerability = 0,
                        decloak = false,
                        targetingPriorityMultiplier = 0,
                        impulseForce = 0,
                    },
                    selfHealRatio = 0,
                    selfDamage = 0,
                    selfHeat = 0,
                    selfImpulseForce = 0,
                    dontFireBelowHealthFraction = 0,
                    resumeFireAboveHealthFraction = 0,
                    dontFireAboveHeatFraction = 0,
                    resumeFireBelowHeatFraction = 0,
                    isResourceMiner = false,
                    isPiercing = false,
                    piercingThreshold = 0,
                    tractorHoldDistance = 0,
                    isAreaOfEffect = false,
                    aoeData = {
                        friendlyFire = false,
                        maximumDegrees = 0,
                        radiusOuter = 0,
                        radiusInner = 0,
                        waveSteps = 0,
                        waveSeconds = 0,
                    },
                    sfxID = 0,
                    SFXIntensity = 0,
                    sizeInUnits = 0.1,
                    lifetime = 0.5,
                    impactSize = 0,
                    impactDuration = 0,
                    disableImpactEffect = false,
                    disableImpactFlash = false,
                    impactColour = { 0, 0, 0, 0 },
                    impactFresnelStrength = 0,
                    disableImpactSizeVariance = false,
                    snapUnitDeathExplosionToImpactPosition = false,
                    impactEffectType = "EXPLOSION",
                    laserDescription = {
                        duration = 0.5,
                        opacity = 0,
                        diameter = 0.1,
                        offset = 0,
                        rotateZ = false,
                        rotateY = false,
                        rotateZUpdate = false,
                        rotateYUpdate = false,
                        noRescaleLength = 0,
                        noFade = false,
                        noShrink = false,
                    },
                    lasersPerShot = 0,
                    barrelCount = 0,
                    barrelSpacing = 0,
                    virtualBarrelOffset = { 0, 0, 0 },
                    barrelIndexCurrent = 0,
                    spawnID = 0,
                    checkForWaypoints = false,
                    ignoreRootVelocity = false,
                    setAutoWaypointTargetToWeaponTarget = false,
                    reloadAmount = 0,
                    secondsPerCycle = 0.02,
                    secondsPerCycleCurrent = 0,
                    shotsPerCycle = 1,
                    shotsPerCycleCurrent = 1,
                    simultaniousShots = 0,
                    secondsPerShot = 0,
                    secondsPerShotCurrent = 0,
                },
                targeting = {
                    acquisition = {
                        type = "QUADTREE_ONLY",
                        isFriendly = false,
                        isResourceMiner = false,
                        acceptFirstValidTarget = false,
                        pauseIfHasTarget = false,
                        ignoreUncapturable = false,
                        ignoreNonHealRequester = false,
                        targetOnlySpecialType = 0,
                        secondsPerScan = 0,
                        ignoreFullHealth = false,
                        minimumHealth = 0,
                        minimumDistance = 0,
                        maximumDistance = 0.1,
                        maximumAngle = 0,
                        addedPreaimDistance = 0,
                        scoreForDistance = 1,
                        scoreForHealth = 0,
                        scoreForHealthCurrent = 0,
                        scoreForHealthCurrentMissing = 0,
                        scoreForHealthCurrentPercentage = 0,
                        scoreForArmour = 0,
                        scoreForArmourCurrent = 0,
                        scoreForAngle = 0,
                        scoreForMountAngle = 0,
                        perceivedHealthMax = 0,
                        perceivedHealthMin = 0,
                        perceivedArmourMax = 0,
                        perceivedArmourMin = 0,
                        perceivedDistanceMin = 0,
                        classMultMissile = 0,
                        classMultDrone = 0,
                        classMultLight = 0,
                        classMultMedium = 0,
                        classMultHeavy = 0,
                        classMultCapital = 0,
                        classMultTitan = 0,
                        shipMultiplier = 0,
                        structureMultiplier = 0,
                        keepTargetMultiplier = 0,
                        scoreBandingSize = 0,
                    },
                    tracking = {
                        workOnNullEntity = false,
                        positionPredictionType = "NONE",
                        predictionVelocityOveride = 0,
                        doAimingComputation = false,
                        canInvalidateTarget = false,
                        invalidationDistance = 0,
                        invalidationAngle = 0,
                        invalidationVelocityHeadOn = 0,
                    },
                },
            },
        },
        {
            name = "Colliders",
            position = { 0, 0, 0.137 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "Body-Tri",
                    position = { 0, 0, -0.129 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Cylinder",
                        center = { 0, 0, -0.12 },
                        radius = 0.55,
                        height = 0.289388,
                        orientation = { 90, 30, 0 },
                        bevelRadius = 1.31,
                        collisionResponse = "None",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "None",
        mass = 1,
        linearDamping = 0.5,
        angularDamping = 0.5,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    ghostMesh = "01_ship_light_tolly/01_ship_light_tolly",
    ghostMaterials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_ship_secondary", "01_MT_Glow_dead", "01_MT_Ghost_TeamColour" },
    ghostParts = {
        {
            name = "glow",
            mesh = "01_ship_light_tolly/01_ship_light_tolly",
            materials = { "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1", "01_MT_buildglow_1" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
        },
    },
    health = {
        unitClass = "LIGHT",
        health = 100,
        health_regen_per_second = 1,
        max_regen_frac = 0,
        armour = 3,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 0.4,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = false,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 0,
        flashSizeOverride = 0,
        forceShockwave = false,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = true,
        deathExplosionAOE = {
            friendlyFire = true,
            maximumDegrees = 0,
            radiusOuter = 2,
            radiusInner = 0.5,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 1,
        },
        deathExplosionFriendlyFire = false,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 2203020,
        invulnerable = false,
        unkillable = false,
        death_countdown = 1,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = false,
    },
    isShield = false,
    isMobile = true,
    movement = {
        type = "MAPLOCKED",
        maximumAngleToTarget = 0.6,
        acceleration = 0.35,
        strafingAccelMultiplier = 0.25,
        reverseAccelMultiplier = 0.75,
        inertialCorrection = true,
        isStrafing = true,
        alwaysThrust = false,
        standoffDistance = 3,
        retreatDistance = 2,
        strafeMargin = 0,
        useMinimumWorldYPosition = false,
        minimumWorldYPosition = 0,
        alwaysFaceCombatTarget = false,
        GoToStructurePlaneForFinalWaypoint = false,
    },
    isRotating = true,
    rotation = {
        turnMode = "Acceleration",
        baseRotationSpeed = 57,
        maxSpeedMultiplier = 0,
        preferredAngle = 0,
        ignoreWorldUp = true,
    },
    doAvoidance = false,
    isRepulsor = true,
    isNotRepulsed = false,
    repulsion = {
        interactionLayer = 0,
        weightOveride = 0,
        colliderDimensionsOverride = { 0, 0, 0 },
    },
    isTargeting = true,
    targetingData = {
        acquisition = {
            type = "QUADTREE_AND_MACRO",
            isFriendly = false,
            isResourceMiner = false,
            acceptFirstValidTarget = false,
            pauseIfHasTarget = false,
            ignoreUncapturable = false,
            ignoreNonHealRequester = false,
            targetOnlySpecialType = 0,
            secondsPerScan = 0.25,
            ignoreFullHealth = false,
            minimumHealth = 0,
            minimumDistance = 0,
            maximumDistance = 15,
            maximumAngle = 0,
            addedPreaimDistance = 0,
            scoreForDistance = 1,
            scoreForHealth = 0,
            scoreForHealthCurrent = 0,
            scoreForHealthCurrentMissing = 0,
            scoreForHealthCurrentPercentage = 0,
            scoreForArmour = 0,
            scoreForArmourCurrent = -0.05,
            scoreForAngle = -0.02,
            scoreForMountAngle = 0,
            perceivedHealthMax = 0,
            perceivedHealthMin = 0,
            perceivedArmourMax = 0,
            perceivedArmourMin = 5,
            perceivedDistanceMin = 0,
            classMultMissile = -1,
            classMultDrone = -1,
            classMultLight = 1.5,
            classMultMedium = 1.25,
            classMultHeavy = 1,
            classMultCapital = 1,
            classMultTitan = 1,
            shipMultiplier = 0,
            structureMultiplier = 0,
            keepTargetMultiplier = 3,
            scoreBandingSize = 0.5,
        },
        tracking = {
            workOnNullEntity = false,
            positionPredictionType = "NONE",
            predictionVelocityOveride = 0,
            doAimingComputation = false,
            canInvalidateTarget = false,
            invalidationDistance = 0,
            invalidationAngle = 0,
            invalidationVelocityHeadOn = 0,
        },
    },
    hasPayload = false,
    isStructure = false,
    structureIgnoreInfluenceControl = false,
    isInfluencer = false,
    isSpawner = false,
    isGenerator = false,
    isCapacitor = false,
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = false,
}
