return {
    unitName = "platform_k35",
    unitDisplayName = "Platform K35",
    unitTooltip = "",
    unitBlurb = "Light Command Platform",
    unitBlurbExcludeFromTooltip = false,
    hotkey = "",
    picture = "1_12012_platform_k35.png",
    controllable = false,
    unselectable = false,
    untargetable = false,
    unhittable = false,
    data = {
        typeID = 2202012,
        factionID = 220,
        macroType = "TRUE",
        cost_matter = 0,
        cost_energy = 0,
        cost_supply = 0,
        cost_time = 0,
        techRequired = 0,
    },
    databankEntry = {
        visibility = "VISIBLE",
        requiredLevelForVisible = "",
        requiredLevelForDescription = "",
        tactical = "",
        description = "<color=yellow>Tactical</color>:\n- Limited self defence against drones and lights.\n- Generates Matter, Energy, and Logistics.\n- Tough, can safely draw enemy fire away from weaker base buildings.\n\n- - -\nInfo\n\nThe steel backbone of Kontaalen military projection within the Spance.\n\nDesigned from the ground up to wage war within the aggressive spancial environment, the K35 is a marvel of astrobaric engineering.\n\nInbuilt cohesion systems, material refineries, drone bays, fabrication arrays, and shielded command-and-control center, rounded off by a modern graviton reactor. The K-series is able to operate for months on it's own, and deploy the most powerful rapid strike doctrines of the Kontaalen Armada. \n\nFurthermore - though some often forget it - there are people on here.  \n\nModerate sacrifices have been made to incorporate humble crew quarters, recreational spaces, sanitation solutions, and a cultivationary for limited food production. \n\nFinally the 400m wide super structure houses it's principle SAIL Drive, SAIL Interdictor, advanced sensor suites, long range communications systems, and shuttle bays. It is also worth noting the presence of a stocked infantry armoury and the layout of hardened fighting positions able to fend off boarding forces with extreme efficacy.",
        weaponInfo = {
            { 2205054, 4, 0 },
        },
    },
    scale = 4,
    colliderDimensions = {
        widthMultiplier = 1,
        heightMultiplier = 1,
        lengthMultiplier = 1,
    },
    inEditor = true,
    autoColourElements = true,
    editorDontColour = false,
    mainMesh = "01_platform_3x3_k35/01_platform_3x3_light",
    materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_teamColour", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_structure_secondary" },
    parts = {
        {
            name = "Spinner",
            mesh = "01_platform_3x3_k35/01_platform_3x3_light_cor",
            materials = { "01_MT_BaseColour_structure_primary", "01_MT_BaseColour_energyGlow" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            rotate = {
                timeStepSeconds = 0,
                degreeRotationPerSecond = { 0, 90, 0 },
            },
        },
        {
            name = "unitBubble(Clone)",
            mesh = "01_platform_3x3_k35/01_platform_3x3_light",
            materials = { "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis", "01_MT_Aegis" },
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1.05, 1.05, 1.05 },
            aegisVisual = true,
        },
        {
            name = "01_prf_pd_turret_sentinel",
            position = { -0.4065, 0.091, 0.4065 },
            rotation = { 0, 315, 0 },
            scale = { 0.0825, 0.0825, 0.0825 },
            weapon = {
                weaponID = 2205054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (1)",
            position = { 0.4065, 0.091, 0.4065 },
            rotation = { 0, 45, 0 },
            scale = { 0.0825, 0.0825, 0.0825 },
            weapon = {
                weaponID = 2205054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (2)",
            position = { 0.4065, 0.091, -0.4065 },
            rotation = { 0, 135, 0 },
            scale = { 0.0825, 0.0825, 0.0825 },
            weapon = {
                weaponID = 2205054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "01_prf_pd_turret_sentinel (3)",
            position = { -0.4065, 0.091, -0.4065 },
            rotation = { 0, 225, 0 },
            scale = { 0.0825, 0.0825, 0.0825 },
            weapon = {
                weaponID = 2205054,
                turnSpeed = 515.662,
                turnMode = "Linear",
                turnInstant = false,
                useParentTarget = false,
                useRootTarget = false,
                targetRootUnit = false,
                mountAngles = {
                    left = 150,
                    right = 150,
                    up = 90,
                    down = 90,
                },
            },
            scaleModifier = true,
            parts = {
                {
                    name = "laser_beam",
                    mesh = "laserbeam/laser_beam",
                    materials = { "MT_LaserBeam" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 0.023296, 0.023296, 0.023296 },
                    weaponVisualConfig = {
                        laserColour = { 0.35, 0.634641, 1, 1 },
                        intensity = 2.5,
                        useWeaponLaserDescription = true,
                        laserDescription = {
                            duration = 0,
                            opacity = 0,
                            diameter = 0,
                            offset = 0,
                            rotateZ = false,
                            rotateY = false,
                            rotateZUpdate = false,
                            rotateYUpdate = false,
                            noRescaleLength = 0,
                            noFade = false,
                            noShrink = false,
                        },
                    },
                    scaleModifier = true,
                },
                {
                    name = "Gun",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_barrel",
                    materials = { "01_MT_BaseColour_ship_primary", "01_MT_BaseColour_teamGlow", "01_MT_BaseColour_ship_secondary" },
                    position = { 0, 0, 0 },
                    rotation = { 0.000003, 0, 0 },
                    scale = { 1, 1, 1 },
                },
                {
                    name = "Body",
                    mesh = "01_turret_sentinel_and_defender/01_turret_platform_sentinel_body",
                    materials = { "01_MT_BaseColour_ship_primary" },
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    turretBody = true,
                },
            },
        },
        {
            name = "colliders",
            position = { 0, 0, 0 },
            rotation = { 0, 0, 0 },
            scale = { 1, 1, 1 },
            parts = {
                {
                    name = "collider",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 0.86, 0.28, 0.86 },
                        orientation = { 0, 45, 0 },
                        bevelRadius = 1.5,
                        collisionResponse = "Collide",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
                {
                    name = "collider (1)",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 1.32, 0.2, 0.24 },
                        orientation = { 0, 45, 0 },
                        bevelRadius = 1.5,
                        collisionResponse = "Collide",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
                {
                    name = "collider (2)",
                    position = { 0, 0, 0 },
                    rotation = { 0, 0, 0 },
                    scale = { 1, 1, 1 },
                    physicsShape = {
                        shapeType = "Box",
                        center = { 0, 0, 0 },
                        size = { 1.32, 0.2, 0.24 },
                        orientation = { 0, 315, 0 },
                        bevelRadius = 1.5,
                        collisionResponse = "Collide",
                        belongsTo = 4294967295,
                        collidesWith = 4294967295,
                        customTags = 0,
                    },
                },
            },
        },
    },
    unitCore = true,
    physicsBody = {
        motionType = "Dynamic",
        smoothing = "Interpolation",
        mass = 1,
        linearDamping = 0.01,
        angularDamping = 0.05,
        initialLinearVelocity = { 0, 0, 0 },
        initialAngularVelocity = { 0, 0, 0 },
        gravityFactor = 0,
        worldIndex = 0,
        customTags = 0,
    },
    physicsShape = {
        shapeType = "Box",
        center = { 0, 0, 0 },
        size = { 1, 1, 0.2 },
        orientation = { 270, 270, 0 },
        bevelRadius = 0.32,
        collisionResponse = "None",
        belongsTo = 4294967295,
        collidesWith = 4294967295,
        customTags = 0,
    },
    health = {
        unitClass = "CAPITAL",
        health = 10000,
        health_regen_per_second = 10,
        max_regen_frac = 0,
        armour = 20,
        armour_regen_per_second = 0,
        armour_max_regen_fraction = 0,
        vulnerability_max = 0,
        shredMultiplier = 0,
        explosionSFX = 0,
        explosionSFXIntensity = 5,
        heatResistancePercentage = 0,
        shredResistancePercentage = 0,
        aegisMaximum = 0,
        isResourceMatter = false,
        isResourceEnergy = false,
        isUncapturable = true,
        isNonHealRequester = false,
        ignoreImpulse = false,
        specialType = 0,
        targetingPriorityMultiplier = 0,
        untargetableTime = 0,
        phaseBlockFraction = 0,
        lifetime = 0,
        explodeOnTimeout = false,
        explosionType = "EXPLOSION",
        explosionDamageRadiusMult = 0,
        explosionSizeOveride = 10,
        flashSizeOverride = 0,
        forceShockwave = true,
        preventShockwave = false,
        preventExplosionSizeVariance = false,
        useDeathExplosionAOEDamage = false,
        deathExplosionAOE = {
            friendlyFire = false,
            maximumDegrees = 0,
            radiusOuter = 0,
            radiusInner = 0,
            waveSteps = 0,
            waveSeconds = 0,
        },
        deathExplosionDamage = {
            isNondamaging = false,
            instances = 0,
            damage = 0,
            piercing = 0,
            shred = 0,
            heat = 0,
            vulnerability = 0,
            decloak = false,
            targetingPriorityMultiplier = 0,
            impulseForce = 0,
        },
        deathExplosionFriendlyFire = true,
        deathUnitSpawnDoNotRandomiseRotation = false,
        deathUnitSpawnTypeID = 2203023,
        invulnerable = false,
        unkillable = false,
        death_countdown = 0,
        mass = 0,
        densityMult = 0,
        tonnage = 0,
        ignoreInstaDeath = false,
        instaDeathThreshold = 0,
        nonRefundable = false,
        alertPlayerOnDeath = true,
    },
    isShield = false,
    isMobile = false,
    isRotating = false,
    doAvoidance = false,
    isRepulsor = false,
    isNotRepulsed = false,
    isTargeting = false,
    hasPayload = false,
    isStructure = true,
    structure = {
        type = "NONE",
        ring = { 0, 0 },
        rectangle = { 4, 4 },
        matrixDimensions = { 0, 0 },
    },
    structureIgnoreInfluenceControl = true,
    isInfluencer = true,
    influence = {
        strength = { 15, 3 },
        ring = { 0, 8 },
        rectangle = { 0, 0 },
        matrixDimensions = { 0, 0 },
    },
    isSpawner = false,
    isGenerator = true,
    resourceGeneration = {
        matter = 2.5,
        energy = 1,
        phase = 0,
    },
    isCapacitor = true,
    resourceCapacity = {
        matter = 300,
        energy = 150,
        phase = 0,
        logistics = 40,
    },
    isStatusEffecter = false,
    isAegisEmitter = false,
    isTechUnlocker = false,
    isTechProjector = false,
    isCommand = true,
    commandType = "CENTRAL",
}
